### ISSUE TITLE
Missing workflow.

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [projectdiscovery/pd-actions#4]
Hello!

I mirrored/copied the repo to my account but now i cannot run the workflow there is no option of running workflow in actions tab... Why?

**Comment by SAGEof6iixPATHS** [comment]
I used this commands to do that :

```
$ git clone --bare https://github.com/projectdiscovery/pd-actions.git
$ cd pd-actions.git
$ git push --mirror https://github.com/username/pd-action.git

```

**Comment by ehsandeep** [comment]
@SAGEof6iixPATHS you need to make any changes in `.github/workflows/pd-actions.yaml` to see action workflow.

**Comment by SAGEof6iixPATHS** [comment]
I am facing a new issue the whole process is completed but while pushing changes it give this error:

> Run ad-m/github-push-action@master
  with:
    branch: refs/heads/main
    directory: .
  env:
    GOROOT: /opt/hostedtoolcache/go/1.14.15/x64
Push to branch refs/heads/main
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

I have edited GITHUB_TOKEN with my token but the error still exists...

**Comment by ehsandeep** [comment]
@SAGEof6iixPATHS you don't need to edit/update the GitHub token.

**Comment by SAGEof6iixPATHS** [comment]
Oh my bad🥺😂
